### PR TITLE
style: 💄 adding title to notes

### PR DESCRIPTION
**Pull request by jurrien-fakkeldij**

### CODE REVIEW

**Review by JesseBrand — CHANGES_REQUESTED** [review]
There are very many style changes here that are not related to the change itself. Would you be able to do this without changing all those extra lines? Maybe adjust the code style settings / linting for this specific project?

I can't see what actually changed now.

**Comment by jurrien-fakkeldij** [comment]
Maybe a good idea to setup a linting configuration then so my linting system just takes the current style without changing too much

**Comment by JesseBrand** [comment]
Very much agreed! Let's set something up.

**Review by JesseBrand — APPROVED** [review]
Awesome!

**Pull request merged**
